// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqxkjwfrtdyvvrkstiay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeGtqd2ZydGR5dnZya3N0aWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzg0MDksImV4cCI6MjA3MzYxNDQwOX0.UEKNPfMD1nY5HsKgxRhUCEDfjLi63kLck_NtVi7Ijm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});